apiVersion: v1
kind: Service
metadata:
  name: herashop
  namespace: default
  labels:
    app: herashop
spec:
  selector:
    app: herashop
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
